load("@rules_java//java:defs.bzl", "java_library")

package(default_package_metadata = ["//:package_metadata"])

java_library(
    name = "ci",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/ci/v1alpha",
    ],
)
