// Copyright 2026 EngFlow, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package engflow.secret.v1;

option go_package = "github.com/EngFlow/engflowapis/go/engflow/secret/v1;secretv1";

option java_multiple_files = true;
option java_outer_classname = "UserSecretsProtos";
option java_package = "com.engflow.secret.v1.proto";

import "engflow/type/compact_digest.proto";

// UserSecrets holds metadata about secret values that are confidential to an
// individual user. The client writes user secrets to a file, encrypts the
// file with a unique key, then stores the encrypted file in the CAS.
//
// To execute an action with user secrets, the client sends this message as
// gRPC metadata "x-engflow-user-secrets-bin" with the Execution/Execute
// request. The client should not send the metadata with other requests.
// The server must not store or log this message and must not store the
// decrypted secrets persistently or expose them to other actions.
//
// This process is unfortunately necessary because gRPC metadata (and HTTP
// headers in general) is limited to a few kilobytes, so it's often not possible
// to pass secrets directly through metadata.
message UserSecrets {
  // The CAS digest of the encrypted ciphertext file.
  engflow.type.CompactDigest ciphertext_digest = 1;

  // The algorithm used to encrypt the ciphertext. Only "aes-256-gcm" is
  // supported. This means the data is encrypted with AES using a 256-bit key
  // in Galois/Counter Mode. The 96-bit nonce is prepended to the ciphertext.
  string algorithm = 2;

  // The key used to decrypt the secrets. Must be 256 bits for "aes-256-gcm".
  bytes key = 3;
}
