load("//bazel:java_rpc_library.bzl", "java_rpc_library")

java_library(
    name = "resourceusage",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/resourceusage/v1",
    ],
)
