load("@rules_java//java:defs.bzl", "java_library")

package(default_package_metadata = ["//:package_metadata"])

java_library(
    name = "eventstore",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/eventstore/v1",
    ],
)
