load("//bazel:java_rpc_library.bzl", "java_rpc_library")

java_library(
    name = "authentication",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/iam/authentication/v1",
    ],
)
