load("//bazel:java_rpc_library.bzl", "java_rpc_library")

java_library(
    name = "resultstore",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/resultstore/v1",
    ],
)
