load("//bazel:java_rpc_library.bzl", "java_rpc_library")

java_library(
    name = "notification",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/notification/v1",
    ],
)
