load("//bazel:java_rpc_library.bzl", "java_rpc_library")

java_library(
    name = "iam",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/iam/authentication",
        "//engflow/iam/v1",
    ],
)
