load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "engflow",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow/api",
        "//engflow/auth",
        "//engflow/cluster",
        "//engflow/eventstore",
        "//engflow/iam",
        "//engflow/notification",
        "//engflow/resourceusage",
        "//engflow/resultstore",
        "//engflow/type",
    ],
)
