load("@rules_java//java:defs.bzl", "java_library")

exports_files(
    [
        "LICENSE",
    ],
    visibility = ["//visibility:public"],
)

java_library(
    name = "engflowapis-java",
    visibility = ["//visibility:public"],
    exports = [
        "//engflow",
    ],
)
