load("@protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "notification",
    visibility = ["//visibility:public"],
    deps = [
        "//engflow/notification/v1",
    ],
)
