load("@io_bazel_rules_go//proto:def.bzl", "go_grpc_library")

package(default_package_metadata = ["@engflowapis//java/internal:license"])

exports_files(
    [
        "LICENSE",
    ],
    visibility = ["//visibility:public"],
)
