proto_library(
    name = "protos",
    visibility = [
        "//:__pkg__",
    ],
    deps = [
        "//engflow/api:protos",
        "//engflow/auth:protos",
        "//engflow/cluster/v1:protos",
        "//engflow/eventstore/v1:protos",
        "//engflow/notification/v1:protos",
        "//engflow/resultstore/v1:protos",
        "//engflow/type:protos",
    ],
)
