proto_library(
    name = "protos",
    visibility = [
        "//third_party/engflowapis:__pkg__",
    ],
    deps = [
        "//third_party/engflowapis/engflow/auth:protos",
        "//third_party/engflowapis/engflow/eventstore/v1:protos",
        "//third_party/engflowapis/engflow/notification/v1:protos",
    ],
)
